services:
  tg-relay-bot:
    container_name: tg-relay-bot
    build:
      context: .
      target: final
    restart: unless-stopped
    environment:
      TELEGRAM_TOKEN: ${TELEGRAM_TOKEN}
      TELEGRAM_SUPER_USERS: ${TELEGRAM_SUPER_USERS}
      HTTP_SECRET: ${HTTP_SECRET}
      HTTP_PORT: 8080
      SMTP_ALLOWED_HOSTS: ${SMTP_ALLOWED_HOSTS}
    expose:
      - 8080
      - 2525
    ports:
      - 2525:2525
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "traefik.http.routers.relay.rule=Host(`relay.${ROOT_DOMAIN}`)"
      - "traefik.http.routers.relay.entrypoints=https"
      - "traefik.http.routers.relay.tls.certresolver=le"
      - "traefik.http.services.relay.loadbalancer.server.port=8080"

networks:
  proxy:
    external: true
