// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"context"
	"github.com/pkarpovich/tg-relay-bot/app/telegram"
	"sync"
)

// TelegramAPIMock is a mock implementation of events.TelegramAPI.
//
//	func TestSomethingThatUsesTelegramAPI(t *testing.T) {
//
//		// make and configure a mocked events.TelegramAPI
//		mockedTelegramAPI := &TelegramAPIMock{
//			GetUpdatesFunc: func(ctx context.Context, offset int, timeoutSec int) ([]telegram.Update, error) {
//				panic("mock out the GetUpdates method")
//			},
//			SendMessageFunc: func(ctx context.Context, chatID int64, text string, parseMode string) error {
//				panic("mock out the SendMessage method")
//			},
//			SendRichMessageFunc: func(ctx context.Context, chatID int64, markdown string) error {
//				panic("mock out the SendRichMessage method")
//			},
//			SetMessageReactionFunc: func(ctx context.Context, chatID int64, messageID int, emoji string) error {
//				panic("mock out the SetMessageReaction method")
//			},
//		}
//
//		// use mockedTelegramAPI in code that requires events.TelegramAPI
//		// and then make assertions.
//
//	}
type TelegramAPIMock struct {
	// GetUpdatesFunc mocks the GetUpdates method.
	GetUpdatesFunc func(ctx context.Context, offset int, timeoutSec int) ([]telegram.Update, error)

	// SendMessageFunc mocks the SendMessage method.
	SendMessageFunc func(ctx context.Context, chatID int64, text string, parseMode string) error

	// SendRichMessageFunc mocks the SendRichMessage method.
	SendRichMessageFunc func(ctx context.Context, chatID int64, markdown string) error

	// SetMessageReactionFunc mocks the SetMessageReaction method.
	SetMessageReactionFunc func(ctx context.Context, chatID int64, messageID int, emoji string) error

	// calls tracks calls to the methods.
	calls struct {
		// GetUpdates holds details about calls to the GetUpdates method.
		GetUpdates []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Offset is the offset argument value.
			Offset int
			// TimeoutSec is the timeoutSec argument value.
			TimeoutSec int
		}
		// SendMessage holds details about calls to the SendMessage method.
		SendMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Text is the text argument value.
			Text string
			// ParseMode is the parseMode argument value.
			ParseMode string
		}
		// SendRichMessage holds details about calls to the SendRichMessage method.
		SendRichMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Markdown is the markdown argument value.
			Markdown string
		}
		// SetMessageReaction holds details about calls to the SetMessageReaction method.
		SetMessageReaction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int
			// Emoji is the emoji argument value.
			Emoji string
		}
	}
	lockGetUpdates         sync.RWMutex
	lockSendMessage        sync.RWMutex
	lockSendRichMessage    sync.RWMutex
	lockSetMessageReaction sync.RWMutex
}

// GetUpdates calls GetUpdatesFunc.
func (mock *TelegramAPIMock) GetUpdates(ctx context.Context, offset int, timeoutSec int) ([]telegram.Update, error) {
	if mock.GetUpdatesFunc == nil {
		panic("TelegramAPIMock.GetUpdatesFunc: method is nil but TelegramAPI.GetUpdates was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Offset     int
		TimeoutSec int
	}{
		Ctx:        ctx,
		Offset:     offset,
		TimeoutSec: timeoutSec,
	}
	mock.lockGetUpdates.Lock()
	mock.calls.GetUpdates = append(mock.calls.GetUpdates, callInfo)
	mock.lockGetUpdates.Unlock()
	return mock.GetUpdatesFunc(ctx, offset, timeoutSec)
}

// GetUpdatesCalls gets all the calls that were made to GetUpdates.
// Check the length with:
//
//	len(mockedTelegramAPI.GetUpdatesCalls())
func (mock *TelegramAPIMock) GetUpdatesCalls() []struct {
	Ctx        context.Context
	Offset     int
	TimeoutSec int
} {
	var calls []struct {
		Ctx        context.Context
		Offset     int
		TimeoutSec int
	}
	mock.lockGetUpdates.RLock()
	calls = mock.calls.GetUpdates
	mock.lockGetUpdates.RUnlock()
	return calls
}

// SendMessage calls SendMessageFunc.
func (mock *TelegramAPIMock) SendMessage(ctx context.Context, chatID int64, text string, parseMode string) error {
	if mock.SendMessageFunc == nil {
		panic("TelegramAPIMock.SendMessageFunc: method is nil but TelegramAPI.SendMessage was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		Text      string
		ParseMode string
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		Text:      text,
		ParseMode: parseMode,
	}
	mock.lockSendMessage.Lock()
	mock.calls.SendMessage = append(mock.calls.SendMessage, callInfo)
	mock.lockSendMessage.Unlock()
	return mock.SendMessageFunc(ctx, chatID, text, parseMode)
}

// SendMessageCalls gets all the calls that were made to SendMessage.
// Check the length with:
//
//	len(mockedTelegramAPI.SendMessageCalls())
func (mock *TelegramAPIMock) SendMessageCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	Text      string
	ParseMode string
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		Text      string
		ParseMode string
	}
	mock.lockSendMessage.RLock()
	calls = mock.calls.SendMessage
	mock.lockSendMessage.RUnlock()
	return calls
}

// SendRichMessage calls SendRichMessageFunc.
func (mock *TelegramAPIMock) SendRichMessage(ctx context.Context, chatID int64, markdown string) error {
	if mock.SendRichMessageFunc == nil {
		panic("TelegramAPIMock.SendRichMessageFunc: method is nil but TelegramAPI.SendRichMessage was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ChatID   int64
		Markdown string
	}{
		Ctx:      ctx,
		ChatID:   chatID,
		Markdown: markdown,
	}
	mock.lockSendRichMessage.Lock()
	mock.calls.SendRichMessage = append(mock.calls.SendRichMessage, callInfo)
	mock.lockSendRichMessage.Unlock()
	return mock.SendRichMessageFunc(ctx, chatID, markdown)
}

// SendRichMessageCalls gets all the calls that were made to SendRichMessage.
// Check the length with:
//
//	len(mockedTelegramAPI.SendRichMessageCalls())
func (mock *TelegramAPIMock) SendRichMessageCalls() []struct {
	Ctx      context.Context
	ChatID   int64
	Markdown string
} {
	var calls []struct {
		Ctx      context.Context
		ChatID   int64
		Markdown string
	}
	mock.lockSendRichMessage.RLock()
	calls = mock.calls.SendRichMessage
	mock.lockSendRichMessage.RUnlock()
	return calls
}

// SetMessageReaction calls SetMessageReactionFunc.
func (mock *TelegramAPIMock) SetMessageReaction(ctx context.Context, chatID int64, messageID int, emoji string) error {
	if mock.SetMessageReactionFunc == nil {
		panic("TelegramAPIMock.SetMessageReactionFunc: method is nil but TelegramAPI.SetMessageReaction was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int
		Emoji     string
	}{
		Ctx:       ctx,
		ChatID:    chatID,
		MessageID: messageID,
		Emoji:     emoji,
	}
	mock.lockSetMessageReaction.Lock()
	mock.calls.SetMessageReaction = append(mock.calls.SetMessageReaction, callInfo)
	mock.lockSetMessageReaction.Unlock()
	return mock.SetMessageReactionFunc(ctx, chatID, messageID, emoji)
}

// SetMessageReactionCalls gets all the calls that were made to SetMessageReaction.
// Check the length with:
//
//	len(mockedTelegramAPI.SetMessageReactionCalls())
func (mock *TelegramAPIMock) SetMessageReactionCalls() []struct {
	Ctx       context.Context
	ChatID    int64
	MessageID int
	Emoji     string
} {
	var calls []struct {
		Ctx       context.Context
		ChatID    int64
		MessageID int
		Emoji     string
	}
	mock.lockSetMessageReaction.RLock()
	calls = mock.calls.SetMessageReaction
	mock.lockSetMessageReaction.RUnlock()
	return calls
}
